add a section with public keys for validation
oauth-wg/oauth-selective-disclosure-jwt pull request #296
Opened 2023-06-15 06:17 UTC by Sakurann

addresses Issue #241.

2023-06-15 06:47 UTC, danielfett commented
The `w3c-vc` example currently uses a different key. We should call that out or change the example to the default key. I think that having one example with a different key (type) doesn't hurt, so we should call out that this example uses a different key.

2023-06-15 12:37 UTC, bc-pi requested changes

2023-06-15 12:37 UTC, bc-pi commented on draft-ietf-oauth-selective-disclosure-jwt.md
> +The following Elliptic Curve public key, represented in JWK format, can be used to validate the Issuer signatures in the above examples (with line wraps within values for display purposes only):
This key doesn't have line wraps within values.

```suggestion
The following Elliptic Curve public key, represented in JWK format, can be used to validate the Issuer signatures in the above examples:
```

2023-06-15 12:37 UTC, bc-pi commented on draft-ietf-oauth-selective-disclosure-jwt.md
> +
The holder public keys can already be found in the example content in the `cnf` claim so don't need to be here.
```suggestion

```

2023-06-15 12:44 UTC, bc-pi commented
> The `w3c-vc` example currently uses a different key. We should call that out or change the example to the default key. I think that having one example with a different key (type) doesn't hurt, so we should call out that this example uses a different key.

Either way, the holder's public key is already available in the payload of the example SD-JWTs. So it doesn't need to be and shouldn't be included here.

2023-06-19 16:32 UTC, danielfett approved these changes
LGTM with Brian's proposed changes.

2023-06-20 02:02 UTC, Sakurann commented on draft-ietf-oauth-selective-disclosure-jwt.md
> +
```suggestion

The public key used to validate a Key Binding JWT can be found in the examples as the content of the `cnf` claim.

```

2023-06-20 02:02 UTC, Sakurann commented
w3c-vc uses a different KB JWT key but the same issuer key, correct?

2023-06-20 11:48 UTC, bc-pi commented
> w3c-vc uses a different KB JWT key but the same issuer key, correct?

Yeah, i believe so. But no signed content is actually shown in that example. That example just shows the payload and disclosure content.

2023-06-20 11:50 UTC, bc-pi approved these changes

2023-06-20 16:16 UTC, merged