Update Rust option in the Implementations list
oauth-wg/oauth-selective-disclosure-jwt pull request #422
Opened 2024-04-17 09:07 UTC by jovfer

Replace old Rust implementation reference (draft v2) with the latest one in OWF.

2024-04-17 12:40 UTC, bc-pi approved these changes

2024-04-30 14:51 UTC, Sakurann approved these changes

2024-04-30 14:54 UTC, Sakurann commented
just reached out to @kushaldas to make sure he is aware of this, just to be sure.

2024-04-30 15:06 UTC, Sakurann requested changes
just until there is a confirmation there is a relationship between this new URL and kushal's one

2024-04-30 18:22 UTC, Sakurann commented on README.md
> + * Rust: [sd-jwt-rs (OWF)](https://github.com/openwallet-foundation-labs/sd-jwt-rust)
```suggestion
 * Rust: [sd_jwt](https://github.com/kushaldas/sd_jwt)
 * Rust: [sd-jwt-rs (OWF)](https://github.com/openwallet-foundation-labs/sd-jwt-rust)
```

2024-04-30 18:23 UTC, Sakurann requested changes
confirmed that the current proposed change was replacing a library by another person, so please add a new line instead of replacing another repo

2024-05-03 17:09 UTC, bc-pi requested changes
> confirmed that the current proposed change was replacing a library by another person, so please add a new line instead of replacing another repo

please fix and also explain the intent

2024-05-15 15:48 UTC, danielfett commented
@jovfer Can you please address the comments/proposed changes above?

2024-05-16 14:53 UTC, jovfer commented
Updated. I'm unsure if it's worth keeping the link to the outdated implementation, but it's probably out of scope for this PR.

2024-06-04 15:10 UTC, bc-pi approved these changes

2024-06-04 15:10 UTC, merged

2024-06-04 15:10 UTC, Sakurann commented
> Updated. I'm unsure if it's worth keeping the link to the outdated implementation, but it's probably out of scope for this PR.

thank you for updating. please do not modify the repositories of other people.