ISO/IEC 29100 is too private
oauth-wg/oauth-selective-disclosure-jwt pull request #475
Opened 2024-10-05 12:12 UTC by bc-pi

https://standards.iso.org/ittf/PubliclyAvailableStandards/index.html no longer has anything for 29100 and https://www.iso.org/standard/45123.html indicates that ISO/IEC 29100:2011 is "Withdrawn" and "Revised by" ISO/IEC 29100:2024 that is now available for the low low special price of CHF 129, which is approximately $150 USD / €137 too much for me to be comfortable referencing

2024-10-09 16:08 UTC, danielfett approved these changes
Takk!

2024-10-09 16:11 UTC, bc-pi commented
> Takk!

That was the first one I didn't recognize. Google says Norwegian, è corretto?

2024-10-09 16:31 UTC, danielfett commented
Det er riktig.

2024-10-11 13:11 UTC, Sakurann commented
Based on Nat's comment, I don't think we need to remove this.

2024-10-12 07:44 UTC, sakimura commented
Just got notified that it is now available from https://standards.iso.org/ittf/PubliclyAvailableStandards/ .

2024-10-15 10:54 UTC, Sakurann requested changes
per Nat's comment the standard is publicly available again :)

2024-10-15 12:11 UTC, bc-pi commented
![Screenshot 2024-10-15 at 6 10 46 AM](https://github.com/user-attachments/assets/dd3c31e5-66d3-4f82-87eb-eb956b6f1822)

![Screenshot 2024-10-15 at 6 11 02 AM](https://github.com/user-attachments/assets/87d80e7c-e00f-469e-8d24-693463cba69f)

2024-10-17 12:00 UTC, bc-pi commented
![Screenshot 2024-10-17 at 5 55 59 AM](https://github.com/user-attachments/assets/05e9d6fe-eb89-4c9b-a79b-9629b3dbe3b8)

I don't think the ISO.29100 reference should have been included in the first place and it's unavailability isn't helping my opinion.

2024-12-18 20:36 UTC, bc-pi commented
https://mailarchive.ietf.org/arch/msg/oauth/SmGW8DevLyuydXAWLPeIgxX4MBo/ mentions this reference again

2024-12-24 23:24 UTC, Sakurann requested changes
I believe what needs to be done is change the reference to 29100:2024 from 29100:2011, not removing the reference

2024-12-27 14:03 UTC, bc-pi commented
> I believe what needs to be done is change the reference to 29100:2024 from 29100:2011, not removing the reference

That's an option too. But have you read all of ISO/IEC 29100:2024 and are all of it's principles applicable to SD-JWT? I don't know, I've only glanced at it. But I don't personally find content like "The privacy principles of [@ISO.29100] should be adhered to." to be particularity helpful in a document like this and think it'd be better off without a vague and general statement to go see this other document that's not easily accessed. That how it's not easily accessed is more a reminder that it, in my opinion anyway, never should have been referenced from SD-JWT in the first place.

2025-01-09 17:17 UTC, danielfett commented
29100 is now available again, it seems.

I share the concern that the current reference is very broad and not actionable at all.

2025-01-16 18:08 UTC, Sakurann approved these changes
I give in to the concern that `current reference is very broad and not actionable at all`.

2025-01-16 18:10 UTC, Sakurann commented on draft-ietf-oauth-selective-disclosure-jwt.md
> +
```suggestion
```

2025-01-16 18:14 UTC, merged