Update main.md
oauth-wg/oauth-selective-disclosure-jwt pull request #92
Opened 2022-06-26 07:29 UTC by sakimura

To address issue #87

2022-06-27 03:13 UTC, Sakurann requested changes
In my understanding, we are not defining a protocol. we are defining an extension to JWT, a way to represent claims. For detailed comment please see Issue #87

2022-07-17 21:20 UTC, Sakurann commented on main.md
> +From the point of view of the collection limitation, which is one of the main privacy principles, it is desirable to be able to provide only the claims necessary for the verifier to process. In the c
How is this text different from what is already in "the introduction"? I would rather have this text as a new "use-cases" section.

Also isn't "data minimization" a more common term than "collection limitation"?

2022-07-17 21:29 UTC, Sakurann commented on main.md
> +A protocol is said to achieve weak uncoverability if the adversary acting as the verifier cannot successfully find the claim values that were not intended to be disclosed to the verifier from the sec
I do not understand " from the section of the release that directly corresponds with the claim". the release will contain the claim value of the claim that is being released.
Could this be clarified/paraphrased, please?

2022-10-13 16:54 UTC, danielfett commented on main.md
> +## R1. Strong uncoverability
Shouldn't that be "Strong Undiscoverability"?

2023-03-13 12:46 UTC, danielfett commented
This has been replaced by PR #225.

2023-03-13 12:46 UTC, closed without merging